"""Validate table Orders

Revision ID: 6c530ec89219
Revises: 655e69cb7ab5
Create Date: 2026-01-18 17:01:33.330334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c530ec89219'
down_revision: Union[str, Sequence[str], None] = '655e69cb7ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('orders', 'delivery_date_end')
    op.drop_column('orders', 'delivery_date_begin')
    op.drop_column('orders', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_date_begin', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_date_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('orders', 'quantity')
    # ### end Alembic commands ###
